routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','user\HomeController@index');

Auth::routes();


//user's routes
Route::get('/home', 'user\HomeController@index')->name('user.home');
Route::get('/user/vfxtype/{id}', 'user\VFXTypeController@index')->name('user.vfxtype');
Route::get('/user/profile/{id}', 'user\HomeController@profile')->name('user.profile');
Route::post('/user/updateprofile/', 'user\HomeController@updateProfile')->name('user.profile.update');
Route::post('/user/delete', 'user\HomeController@deleteUser')->name('user.delete');
Route::post('/user/changepassword', 'user\HomeController@changePassword')->name('user.profile.changepassword');

Route::get('/user/vfxtypeform', 'user\VFXTypeController@vfxForm')->name('user.vfxtypeform');
Route::post('/user/vfxtypeform', 'user\VFXTypeController@addvfxForm')->name('user.vfxtypeform');
Route::post('/user/vfxgroup/autocomplete', 'user\VFXTypeController@getVFXGroup')->name('user.vfxgroup.autocomplete');

Route::post('/user/vfxtype/autocomplete', 'user\VFXTypeController@getVFX')->name('user.vfxtype.autocomplete');
Route::post('/user/screencredit/autocomplete', 'user\VFXTypeController@getCreditlist')->name('user.screencredit.autocomplete');
Route::post('/user/tag/autocomplete', 'user\VFXTypeController@getTag')->name('user.tag.autocomplete');
Route::post('/user/vfxtypelist', 'user\VFXTypeController@vfxList')->name('user.vfxtypelist');
Route::post('/user/savesearch','user\VFXTypeController@saveSearch')->name('user.savesearch');
Route::post('/user/savesearchresult','user\VFXTypeController@saveSearchResult')->name('user.savesearchresult');
Route::post('/user/contact/delete','user\VFXTypeController@deleteVfxContact')->name('user.contact.delete');

//Update Scene note
Route::post('/user/scenenote/update','user\VFXTypeController@updateSceneNote')->name('user.scenenote.update');
Route::post('/user/scenedid/update','user\VFXTypeController@updateSceneDid')->name('user.scenedid.update');


//user roles
Route::post('/user/rolelist','user\VFXTypeController@roleList')->name('user.rolelist');
Route::post('/roles','Auth\RegisterController@roleList')->name('register.rolelist');
Route::post('/user/scenerole/add','user\VFXTypeController@addSceneRole')->name('user.scenerole.add');

//tags routes
Route::post('/taglist','user\TagController@autoComplete')->name('user.taglist');
Route::post('/addtag','user\VFXTypeController@addTag')->name('user.addtag');

//save playlist
Route::post('/saveplaylist','user\VFXTypeController@savePlaylist')->name('user.saveplaylist');
 Route::post('/playlist/delete','user\PlayListController@deletePlaylist')->name('user.playlist.delete');
//playlist routes
Route::get('/playlist/', 'user\PlayListController@index')->name('user.playlist.index');
Route::post('/playlist/list','user\PlayListController@list')->name('user.playlist.list');
//vfx group's routes
Route::post('/vfxgroup','user\VFXTypeController@vfxGroup')->name('user.vfxgroup');


//vfx types routes
Route::post('/vfxslist/{id?}','user\VFXTypeController@vfxTypeList')->name('user.vfxslist');
Route::post('/projecttypelist','user\VFXTypeController@projectTypeList')->name('user.projecttypelist');
Route::post('/tagslist','user\VFXTypeController@tagsList')->name('user.tagslist');
Route::post('/scenetag/change','user\VFXTypeController@changeSceneTag')->name('user.scenetag.change');
Route::post('/scenetag/remove','user\VFXTypeController@removeSceneTag')->name('user.scenetag.remove');
Route::post('vfxgroup/focusout','user\VFXTypeController@focusoutVFXGroup')->name('user.vfxgroup.focusout');
Route::post('vfxtype/focusout','user\VFXTypeController@focusoutVFXType')->name('user.vfxtype.focusout');
Route::post('screencredit/focusout','user\VFXTypeController@focusoutScreenCredit')->name('user.screencredit.focusout');
Route::post('scenerole/change','user\VFXTypeController@ChangeSceneRole')->name('user.scenerole.change');
Route::post('projecttype/focusout','user\VFXTypeController@focusoutProjectType')->name('user.projecttype.focusout');
Route::post('project/focusout','user\VFXTypeController@focusoutProject')->name('user.project.focusout');
Route::post('year/focusout','user\VFXTypeController@focusoutYear')->name('user.year.focusout');
Route::post('link/focusout','user\VFXTypeController@focusoutLink')->name('user.link.focusout');
Route::post('rating/focusout','user\VFXTypeController@focusoutRating')->name('user.rating.focusout');
Route::post('/searchvfxtype','user\VFXTypeController@searchVFXType')->name('user.searchvfxtype');
Route::post('/searchvfxgroup','user\VFXTypeController@searchVFXGroup')->name('user.searchvfxgroup');
Route::post('/searchtag','user\VFXTypeController@searchTag')->name('user.searchtag');
//search routes
  Route::get('/search','user\VFXTypeController@viewSearch')->name('user.search'); 
  Route::post('/searchlist','user\VFXTypeController@searchList')->name('user.searchlist');
  
  Route::post('/deletesearch','user\VFXTypeController@deleteSearch')->name('user.deletesearch');
  Route::get('/searchresult/{id}','user\VFXTypeController@showSearch')->name('user.search.searchresult');
  Route::get('/playlist/{url}','user\MyPlaylistController@showPlaylist')->name('user.searchresult');
  Route::get('/myplaylist/','user\MyPlaylistController@myPlayList')->name('user.myplaylist');



  
//admin's routes
Route::get('/admin/', 'Auth\AdminController@showLoginForm');
Route::get('/admin/login', 'Auth\AdminController@showLoginForm');
Route::post('/admin/login','Auth\AdminController@login')->name('admin.login');
Route::post('/admin/logout','Auth\AdminController@logout')->name('admin.logout');
  Route::group(['prefix'=> 'admin', 'namespace'=> 'admin', 'middleware'=> 'auth:admin','as'=>'admin.'], function() {
  



//user's routes
    Route::get('user', 'UserController@index')->name('user');
    Route::post('userlist', 'UserController@getUserList')->name('userlist');
    Route::post('user/rolelist', 'UserController@roleList')->name('user.rolelist');

    Route::post('adduser','UserController@addUser')->name('user.add');
    Route::post('edituser','UserController@editUser')->name('user.edit');
    Route::post('edituserpassword','UserController@editUserPassword')->name('user.edituserpassword');
    Route::post('updateuser','UserController@updateUser')->name('user.update');
    Route::post('changeapproval', 'UserController@changeApproval')->name('changeapproval');
//vfx groups
    Route::get('vfxgrouptype', 'VFXtypeGroupController@index')->name('vfxgrouptype');
    Route::post('vfxgroup/list','VFXtypeGroupController@list')->name('vfxgroup.list');
    Route::post('vfxgroup/add','VFXtypeGroupController@add')->name('vfxgroup.add');
    Route::post('vfxgroup/delete','VFXtypeGroupController@delete')->name('vfxgroup.delete');
    Route::post('vfxgroup/edit','VFXtypeGroupController@edit')->name('vfxgroup.edit');
    Route::post('vfxgroup/update','VFXtypeGroupController@update')->name('vfxgroup.update');
    
//vfx type
    Route::get('vfxtype', 'VFXController@index')->name('vfxtype');
    Route::post('vfxtype/list','VFXController@list')->name('vfxtype.list');
    Route::post('vfxtype/add','VFXController@add')->name('vfxtype.add');
    Route::post('vfxtype/edit','VFXController@edit')->name('vfxtype.edit');
    Route::post('vfxtype/update','VFXController@update')->name('vfxtype.update');
    Route::post('vfxtype/delete','VFXController@delete')->name('vfxtype.delete');

    //vfx type
    Route::get('projecttype', 'ProjectTypeController@index')->name('projecttype');
    Route::post('projecttype/list','ProjectTypeController@list')->name('projecttype.list');
    Route::post('projecttype/add','ProjectTypeController@add')->name('projecttype.add');
    Route::post('projecttype/edit','ProjectTypeController@edit')->name('projecttype.edit');
    Route::post('projecttype/update','ProjectTypeController@update')->name('projecttype.update');
    Route::post('projecttype/delete','ProjectTypeController@delete')->name('projecttype.delete');

//tags
    Route::get('tag', 'TagController@index')->name('tag');
    Route::post('tag/list','TagController@list')->name('tag.list');
    Route::post('tag/add','TagController@add')->name('tag.add');
    Route::post('tag/edit','TagController@edit')->name('tag.edit');
    Route::post('tag/update','TagController@update')->name('tag.update');
    Route::post('tag/delete','TagController@delete')->name('tag.delete');
    

    Route::post('vfxgroup','VFXController@vfxGroup')->name('vfxtype.vfxgroup');

//admin role
  Route::get('role', 'RoleController@index')->name('role');  
  Route::post('role/list','RoleController@list')->name('role.list');
  Route::post('role/add','RoleController@add')->name('role.add');
  Route::post('role/delete','RoleController@delete')->name('role.delete');
  Route::post('role/edit','RoleController@edit')->name('role.edit');
  Route::post('role/update','RoleController@update')->name('role.update'); 
  });

resources/views/admin/projecttypes.blade.php
@extends('admin.layouts.app')
@section('content')
<div class="users_datatablebox">
	<div class="signeup_lefttextbox">
		<p>Project Type</p>
	</div>
	<div class="addbtnbox">
		  <button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal">Add</button>
	</div>
	<table class="table table-striped table-hover" style="width: 100%;" id="dataTable">
		<thead>
			<tr>
				<th>Number</th>
				<th>Type</th>
				<th>Action</th>
			</tr>
		</thead>
		<tbody>
		</tbody>
	</table>
</div>
<!-- Modal -->
<div class="modal fade" id="myModal" role="dialog">          
  <div class="modal-dialog">
    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Add Project Type</h4>
      </div>
      <div class="modal-body">
        <form id="addprojecttypeform" enctype="multipart/form-data" method="post">

          <div class="form-group">
            <input type="text" name="type" id="addprojecttype" class="form-control" placeholder="Enter Project type">
          </div>
         
          <!-- <div class="form-group">
          	<img id="addimage" src="#" alt="" />
            <input type="file" name="image" accept="image/*" class="required"    onchange="readURL(this);"  />
          </div> -->
          <div class="form-group">
            <!-- <a  class="btn btn-default" onclick="UpdateIndustry()">Update</a>  --> 
            <a  class="btn btn-default" onclick="AddProject()">Add</a>
          
          </div>
          </form>
          <div class="modal-footer">

          </div>
        </div>
      </div>
    </div> 
  </div>

  <!--Edit Modal -->
  <div class="modal fade" id="editModal" role="dialog">          
    <div class="modal-dialog">
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Edit Project</h4>
        </div>
        <div class="modal-body">
          <form id="updateprojectform"  method="post">

            <div class="form-group">
             <input type="hidden" name="id" id="editprojectid">	
              <input type="text" name="type" id="ediprojecttype" class="form-control" placeholder="Enter Project Type">
            </div>
           
            <!-- <div class="form-group">
            	<img id="addimage" src="#" alt="" />
              <input type="file" name="image" accept="image/*" class="required"    onchange="readURL(this);"  />
            </div> -->
            <div class="form-group">
              <!-- <a  class="btn btn-default" onclick="UpdateIndustry()">Update</a>  --> 
              <a  class="btn btn-default" onclick="UpdateProject()">Update</a>
            
            </div>
            </form>
            <div class="modal-footer">

            </div>
          </div>
        </div>
      </div> 
    </div>
@endsection
@section('js')
	<script type="text/javascript">
		var table   =  $('#dataTable').DataTable({
	              ajax: {
	                            type: "post",
	                            url: "{{route('admin.projecttype.list') }}",
	                            data: function ( d ) {
	                                d._token = "{{ csrf_token() }}";
	                            }
	                             
	                        },
	                        columns:[
	                           { data:'DT_RowIndex',name:'id'},
	                           { data:'type',name:'type'},
	                           { data:action,name:'action'},
	                          
	                          
	                          
	                          
	                         ]
	              });

		function action(data){
		  return '<a href="javascript:void(0);" class="editbtn" onclick="editprojecttype('+data.id+')" data-toggle="modal" data-target="#editModal"><img src="{{ asset("public/assets/Admin/svg/edit.svg") }}" alt=""></a> <a href="javascript:void(0);" class="deletebtn" data-id="'+data.id+'" data-toggle="confirmation" data-title="Are You Sure?" data-popout="true" data-singleton="true"><img src="{{ asset("public/assets/Admin/svg/delete-button.svg") }}" alt=""></a>';
		}

		function AddProject()
		{
		   $('#addprojecttypeform').submit();
		}

		$('#addprojecttypeform').validate({ // initialize the plugin
		       rules: {
		           type: {
		               required:true,
		             
		           },
		       },
		       submitHandler: function(form) {
		       		$.LoadingOverlay("show",{
		       			  image       : "",
		       			  text        : "inserting..."
		       		});
		         		var formData = $('#addprojecttypeform').serialize();
		         		 //var formData = $( "#category_form" ).serializeArray();
		         		     
		         		 $.ajaxSetup({
		         		   headers: {'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')}
		         		 });
		         		 $.ajax({
		         		     type:'POST',
		         		     url:'{{route("admin.projecttype.add")}}',
		         		   
		         		     data: formData,

		         		     beforeSend:function(){},
		         		     success:function(data) {
		         		     	  $.LoadingOverlay("hide");
		         		         if (data.status==true) {
		         		            toastr.success(data.message);
		         		            table.ajax.reload();
		         		            $('#myModal').modal('toggle');
		         		             $('#addprojecttypeform')[0].reset();
		         		         } else {                              toastr.error(data.message);  
		         		            
		         		         }
		         		     },
		         		 });
		        }
		   });  

		table.on( 'draw', function () {
		    jQuery('[data-toggle=confirmation]').confirmation({
		      rootSelector: '[data-toggle=confirmation]',
		        onConfirm: function(value) {
		          id = $(this).data('id');
		          $.ajax({
		              url: '{{route("admin.projecttype.delete")}}',
		              method: 'POST',
		              data: { 
		                    id:id,
		                    _token: "{{ csrf_token() }}"
		                  }, 
		              }).done( function( result ){
		             toastr.success(result.message);
		             table.ajax.reload();
		          });
		        },
		        
		    });
		} );

		function editprojecttype(id){
		  $.ajaxSetup({
		    headers: {'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')}
		  });
		  $.ajax({
		      url: '{{route("admin.projecttype.edit")}}',
		      method: 'POST',
		      data: { 
		            id:id,
		          }, 
		      }).done( function( result ){
		      $('#editprojectid').val(result.id);
		      $('#ediprojecttype').val(result.type);
		  });
		}

		function UpdateProject()
		{
		   $('#updateprojectform').submit();
		}

		$('#updateprojectform').validate({ // initialize the plugin
		       rules: {
		           role: {
		               required:true,
		             
		           },
		       },
		       submitHandler: function(form) {
		       		$.LoadingOverlay("show",{
		       			  image       : "",
		       			  text        : "updating..."
		       		});
		         		var formData = $('#updateprojectform').serialize();
		         		 //var formData = $( "#category_form" ).serializeArray();
		         		     
		         		 $.ajaxSetup({
		         		   headers: {'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')}
		         		 });
		         		 $.ajax({
		         		     type:'POST',
		         		     url:'{{route("admin.projecttype.update")}}',
		         		   
		         		     data: formData,

		         		     beforeSend:function(){},
		         		     success:function(data) {
		         		     	  $.LoadingOverlay("hide");
		         		         if (data.status==true) {
		         		            toastr.success(data.message);
		         		            table.ajax.reload();
		         		            $('#editModal').modal('toggle');
		         		           $('#updateprojectform')[0].reset();
		         		         } else {                              
		         		         	toastr.error(data.message);  
		         		            
		         		         }
		         		     },
		         		 });
		        }
		   });  

	</script>
@endsection		

resources/views/admin/user.blade.php
@extends('admin.layouts.app')
@section('content')
<div class="users_datatablebox">
	<div class="signeup_lefttextbox">
		<p>Users</p>
	</div>
	<div class="addbtnbox">
	  <button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal">Add</button>
	</div>
	<table class="table table-striped table-hover" style="width: 100%;" id="dataTable">
		<thead>
			<tr>
				<th>Number</th>
				<th>Name</th>
				<th>Email</th>
				<th>User Name</th>
				<th>Approval</th>
				<th>Action</th>
			</tr>
		</thead>
		<tbody>
		
		</tbody>
	</table>
</div>

<!-- Modal -->
<div class="modal fade" id="myModal" role="dialog">          
  <div class="modal-dialog">
    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Add User</h4>
      </div>
      <div class="modal-body">
        <form id="userform" enctype="multipart/form-data" method="post">

          <div class="form-group">
            <input type="text" name="name" id="addcompanyname" class="form-control" placeholder="Enter Name">
          </div>
          <div class="form-group">
            <input type="text" name="user_name" id="addusername" class="form-control" placeholder="Enter User Name">
          </div>
          
          <div class="form-group">
            <input type="text" name="email" id="" class="form-control" placeholder="Enter Email">
          </div>

          <div class="form-group">
            <input type="text" name="phone" id="" class="form-control" placeholder="Enter Phone">
          </div> 

          <div class="form-group">
            <input type="text" name="bio" id="" class="form-control" placeholder="Enter Short Bio">
          </div>

          <div class="form-group">
            	<select name="role_id" id="addroleid">
            		<option></option>
                </select>
          </div>
       
          <!-- <div class="form-group">
          	<img id="addimage" src="#" alt="" />
            <input type="file" name="image" accept="image/*" class="required"    onchange="readURL(this);"  />
          </div> -->
          <div class="form-group">
            <!-- <a  class="btn btn-default" onclick="UpdateIndustry()">Update</a>  --> 
            <a  class="btn btn-default" onclick="AddUser()">Add</a>
          
          </div>
          </form>
          <div class="modal-footer">

          </div>
        </div>
      </div>
    </div> 
  </div>

  <!--Edit Modal -->
  <div class="modal fade" id="editModal" role="dialog">          
    <div class="modal-dialog">
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Edit User</h4>
        </div>
        <div class="modal-body">
          <form id="edituserform" enctype="multipart/form-data" method="post">

            <div class="form-group">
              <input type="hidden" name="id" id="editid">
              <input type="text" name="name" id="editname" class="form-control" placeholder="Enter Name">
            </div>
            <div class="form-group">
              <input type="text" name="user_name" id="editusername" class="form-control" placeholder="Enter User Name">
            </div>
            
            <div class="form-group">
              <input type="text" name="email" id="editemail" class="form-control" placeholder="Enter Email">
            </div>

            <div class="form-group">
              <input type="text" name="phone" id="editphone" class="form-control" placeholder="Enter Phone">
            </div> 

            <div class="form-group">
              <input type="text" name="short_bio" id="editbio" class="form-control" placeholder="Enter Short Bio">
            </div>

            <div class="form-group">
              	<select name="role_id" id="editroleid">
              		<option></option>
                  </select>
            </div>
         
            <!-- <div class="form-group">
            	<img id="addimage" src="#" alt="" />
              <input type="file" name="image" accept="image/*" class="required"    onchange="readURL(this);"  />
            </div> -->
            <div class="form-group">
              <!-- <a  class="btn btn-default" onclick="UpdateIndustry()">Update</a>  --> 
              <a  class="btn btn-default" onclick="EditUserSubmit()">Update</a>
            
            </div>
            </form>
            <div class="modal-footer">

            </div>
          </div>
        </div>
      </div> 
    </div>
@endsection
@section('js')
	<script type="text/javascript">
		
	  	//getting Data

	  var table   =  $('#dataTable').DataTable({
	              ajax: {
	                            type: "post",
	                            url: "{{route('admin.userlist') }}",
	                            data: function ( d ) {
	                                d._token = "{{ csrf_token() }}";
	                            }
	                             
	                        },
	                        columns:[
	                           { data:'DT_RowIndex',name:'id'},
	                           { data:'name',name:'name'},
	                           { data:'email',name:'email'},
	                           { data:'user_name',name:'user_name'},
	                           { data:'approval',name:'approval'},
	                           { data:action,name:'action'},
	                          
	                          
	                          
	                         ]
	              });

	  function action(data){
	    return '<a href="javascript:void(0);" class="editbtn" onclick="edituser('+data.id+')" data-toggle="modal" data-target="#editModal"><img src="{{ asset("public/assets/Admin/svg/edit.svg") }}" alt=""></a><a href="javascript:void(0);" class="editbtn" onclick="edituserpassword('+data.id+')"><img src="{{ asset("public/assets/Admin/images/reset.png") }}" alt="" title="Reset Password"></a>';
	  }


	 

	  //edit user password
	  function edituserpassword(id){
	  	$.LoadingOverlay("show",{
	  		  image       : "",
	  		  text        : "password resetting..."
	  	});
	  	$.ajaxSetup({
	  	  headers: {'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')}
	  	});
	  	$.ajax({
	  	    url: '{{route("admin.user.edituserpassword")}}',
	  	    method: 'POST',
	  	    data: { 
	  	          id:id,
	  	        }, 
	  	    }).done( function( result ){
	  	    $.LoadingOverlay("hide");
	  	    toastr.success(result.message);
	  	});
	  }

	  //edit user
	  function edituser(id){
	  	$.ajaxSetup({
	  	  headers: {'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')}
	  	});
	  	$.ajax({
	  	    url: '{{route("admin.user.edit")}}',
	  	    method: 'POST',
	  	    data: { 
	  	          id:id,
	  	        }, 
	  	    }).done( function( result ){
	  	    $('#editid').val(result.id);
	  	    $('#editname').val(result.name);
	  	    $('#editusername').val(result.user_name);
	  	    $('#editemail').val(result.email);
	  	    $('#editphone').val(result.phone);
	  	    $('#editbio').val(result.short_bio);
	  	    $("#editroleid").val(result.role_id).trigger('change');
	  	});
	  }

	  	//changing approval permission 
	  	$(document).on("click", ".approval", function(){
	 		id    = $(this).data('id')
	 		value = $(this).data('value')
	 		if(value == 'yes'){
	 			value = 'no';
	 		}
	 		else{
	 			value = 'yes';
	 		}
	 		$.ajaxSetup({
	 		  headers: {'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')}
	 		});
	 		$.ajax({
	 		    type:'POST',
	 		    url:'{{route("admin.changeapproval")}}',
	 		    data: {id:id,value:value},
	 		    success:function(data) {
	 		    	toastr.success(data.message);
	 		    	table.ajax.reload();	
	 		    },
	 		});		
	  	});

	  	function AddUser()
	  	{
	  	   $('#userform').submit();
	  	}  

	  	$('#userform').validate({ // initialize the plugin
	  	       rules: {
	  	           name: {
	  	               required:true,
	  	             
	  	           },
	  	           user_name: {
	  	               required:true,
	  	              
	  	           },
	  	           email:{
	  	           		required:true,
	  	           		email:true
	  	           },
	  	           phone:{
	  	           		required:true,
	  	           },
	  	          

	  	       },
	  	       submitHandler: function(form) {
	  	       		$.LoadingOverlay("show",{
	  	       			  image       : "",
	  	       			  text        : "inserting..."
	  	       		});
	  	         		var formData = $('#userform').serialize();
	  	         		 //var formData = $( "#category_form" ).serializeArray();
	  	         		     
	  	         		 $.ajaxSetup({
	  	         		   headers: {'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')}
	  	         		 });
	  	         		 $.ajax({
	  	         		     type:'POST',
	  	         		     url:'{{route("admin.user.add")}}',
	  	         		   
	  	         		     data: formData,

	  	         		     beforeSend:function(){},
	  	         		     success:function(data) {
	  	         		     	  $.LoadingOverlay("hide");
	  	         		         if (data.status==true) {
	  	         		            toastr.success(data.message);
	  	         		            table.ajax.reload();
	  	         		            $('#myModal').modal('toggle');
	  	         		             $('#userform')[0].reset();
	  	         		         } else {                              
	  	         		         	toastr.error(data.message);  
	  	         		         }
	  	         		     },
	  	         		 });
	  	        }
	  	   });

	  	$(document).ready(function(){
	  		//role list
	  		$('#addroleid').select2({		
		       placeholder: 'Select Role'
		   });

	  		$('#editroleid').select2({		
		       placeholder: 'Select Role'
		   });
	  		$.ajaxSetup({
	  		    headers: {
	  		        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
	  		    }
	  		});
	  		$.ajax({
	  		   url:"{{route('admin.user.rolelist')}}",
	  		   type:"POST",
	  		  
	  		   success:function(data){
	  		       $.each(data,function(key, value)
	  		                     {
	  		                         $("#addroleid").append('<option value=' + value.id + '>' + value.role + '</option>'); 
	  		                         $("#editroleid").append('<option value=' + value.id + '>' + value.role + '</option>'); 
	  		                        
	  		                     });
	  		       
	  		        }
	  		});
	  	});


	  	function EditUserSubmit()
	  	{
	  	   $('#edituserform').submit();
	  	}  

	  	$('#edituserform').validate({ // initialize the plugin
	  	       rules: {
	  	           name: {
	  	               required:true,
	  	             
	  	           },
	  	           user_name: {
	  	               required:true,
	  	              
	  	           },
	  	           email:{
	  	           		required:true,
	  	           		email:true
	  	           },
	  	           phone:{
	  	           		required:true,
	  	           },
	  	          

	  	       },
	  	       submitHandler: function(form) {
	  	       		$.LoadingOverlay("show",{
	  	       			  image       : "",
	  	       			  text        : "updating..."
	  	       		});
	  	         		var formData = $('#edituserform').serialize();
	  	         		 //var formData = $( "#category_form" ).serializeArray();
	  	         		     
	  	         		 $.ajaxSetup({
	  	         		   headers: {'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')}
	  	         		 });
	  	         		 $.ajax({
	  	         		     type:'POST',
	  	         		     url:'{{route("admin.user.update")}}',
	  	         		   
	  	         		     data: formData,

	  	         		     beforeSend:function(){},
	  	         		     success:function(data) {
	  	         		     	  $.LoadingOverlay("hide");
	  	         		         if (data.status==true) {
	  	         		            toastr.success(data.message);
	  	         		            table.ajax.reload();
	  	         		            $('#editModal').modal('toggle');
	  	         		             $('#edituserform')[0].reset();
	  	         		         } else {                              
	  	         		         	toastr.error(data.message);  
	  	         		         }
	  	         		     },
	  	         		 });
	  	        }
	  	   });
	  </script> 
@endsection	             